* fcitx-remote OS X

** fcitx-remote
fcitx-remote is a tool for control fcitx state via console.Users in Linux use it for interact with their vim or emacs to avoid being interrupted by input method.

** Plugins
+ +Vim: [[http://www.vim.org/scripts/script.php?script_id=3764][fcitx.vim - keep and restore fcitx state when leaving/re-entering insert mode : vim online]] (not supported for now,this is next to do)+

+ Vim: [[https://github.com/CodeFalling/fcitx-vim-osx][CodeFalling/fcitx-vim-osx]] ,this is a modified version =fcitx.vim= works well with =fcitx-remote-osx=.Also works with =fcitx= in Linux.

+ Emacs: [[https://github.com/cute-jumper/fcitx.el][cute-jumper/fcitx.el]]

** How this works
fcitx-remote for OS X dosen't reply on fcitx at all.It just a small program respond to fcitx.el etc just like it's really fcitx-remote in Linux.

You can choose your Chinese input method and English layout(or others) in compile.

* Install

** brew tap
```shell
brew tap codefalling/fcitx-remote-for-osx
brew install codefalling/fcitx-remote-for-osx/fcitx-remote-for-osx --with-baidu-pinyin
```

`--with-baidu-pinyin` means install for Baidu-pinyin Input Method.

You can use `brew info codefalling/fcitx-remote-for-osx/fcitx-remote-for-osx` to get more options info for input method support.

```
==> Options
--with-baidu-pinyin
	Build fcitx-remote for osx with baidu-pinyin support
--with-baidu-wubi
	Build fcitx-remote for osx with baidu-wubi support
--with-osx-pinyin
	Build fcitx-remote for osx with osx-pinyin support
--with-qq-wubi
	Build fcitx-remote for osx with qq-wubi support
--with-sogou-pinyin
	Build fcitx-remote for osx with sogou-pinyin support
--with-squirrel-rime
	Build fcitx-remote for osx with squirrel-rime support
```
** Manual Install
#+BEGIN_SRC shell
  git clone https://github.com/CodeFalling/fcitx-remote-for-osx
  cd fcitx-remote-for-osx
  xcodebuild GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS CHINNESE_KEYBOARD_LAYOUT=@\"com.baidu.inputmethod.BaiduIM.pinyin\"' install
#+END_SRC

=com.baidu.inputmethod.BaiduIM.pinyin= is imname of Baidu Pinyin inputmethod.

You can use =fcitx-remote -n= to get imname of current inputmethod.

| Inputmethod   | imname                                           |
| Baidu Pinyin  | com.baidu.inputmethod.BaiduIM.pinyin             |
| Baidu Wubi    | com.baidu.inputmethod.BaiduIM.wubi               |
| Sougou Pinyin | com.sogou.inputmethod.sogou.pinyin               |
| QQ Wubi       | com.tencent.inputmethod.QQInput.QQWubi           |
| Squirrel Rime | com.googlecode.rimeime.inputmethod.Squirrel.Rime |
| OS X Pinyin   | com.apple.inputmethod.SCIM.ITABC                 |

Feel free to perfecting this table,issue or pull&requests is fine.

** Prebuild binary
If you don't want to install XCode.You can also download pre-build binary from +https://github.com/CodeFalling/fcitx-remote-for-osx/releases/tag/0.0.1 ，unzip and+ https://github.com/CodeFalling/fcitx-remote-for-osx/tree/binary ,then rename =fcitx-remote= and copy to =/usr/local/bin/=.

Please let me know if something not work.
* Trouble shooting

+My emacs hangs when I press =C-xC-f= in my spacemacs with this project and =fcitx.el=.Actually I don't know why,but =(fcitx-prefix-keys-setup)= and =(fcitx-prefix-keys-turn-on)= cause this. Good news is we just now need them in OS X beacuse most inputmethod in OS X dosen't block second key like fcitx. So just *don't* use them.+

+ My Emacs got hanged when press C-x C-f

Just add =(setq shell-file-name "bash")= to your =.emacs=.

* TODOS
- [X] fcitx.vim support
